apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: Service
    name: small-go-api
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30082